const outputs = {
    '주용도코드명': ['mainPurpsCdNm'],
    '기타용도': ['etcPurps'],
    '지붕코드': ['roofCd'],
    '지붕코드명': ['roofCdNm'],
    '기타지붕': ['etcRoof'],
    '가구수': ['fmlyCnt', '가구'],
    '높이': ['heit', 'm'],
    '지상층수': ['grndFlrCnt'],
    '지하층수': ['ugrndFlrCnt'],
    '승용승강기수': ['rideUseElvtCnt'],
    '비상용승강기수': ['emgenUseElvtCnt'],
    '부속건축물수': ['atchBldCnt'],
    '부속건축물면적': ['atchBldArea', '㎡'],
    '총동연면적': ['totDongTotArea', '㎡'],
    '옥내기계식수': ['indrMechUtcnt', '대'],
    '옥내기계식면적': ['indrMechArea', '㎡'],
    '옥외기계식수': ['oudrMechUtcnt', '대'],
    '옥외기계식면적': ['oudrMechArea', '㎡'],
    '옥내자주식수': ['indrAutoUtcnt', '대'],
    '옥내자주식면적': ['indrAutoArea', '㎡'],
    '옥외자주식수': ['oudrAutoUtcnt', '대'],
    '옥외자주식면적': ['oudrAutoArea', '㎡'],
    '허가일': ['pmsDay'],
    '착공일': ['stcnsDay'],
    '사용승인일': ['useAprDay'],
    '허가번호년': ['pmsnoYear'],
    '허가번호기관코드': ['pmsnoKikCd'],
    '허가번호기관코드명': ['pmsnoKikCdNm'],
    '허가번호구분코드': ['pmsnoGbCd'],
    '허가번호구분코드명': ['pmsnoGbCdNm'],
    '호수': ['hoCnt', '호'],
    '에너지효율등급': ['engrGrade'],
    '에너지절감율': ['engrRat'],
    'EPI점수': ['engrEpi'],
    '친환경건축물등급': ['gnBldGrade'],
    '친환경건축물인증점수': ['gnBldCert'],
    '지능형건축물등급': ['itgBldGrade'],
    '지능형건축물인증점수': ['itgBldCert'],
    '생성일자': ['crtnDay'],
    'null': ['Items'],
    '순번': ['rnum'],
    '지위치': ['platPlc'],
    '시군구코드': ['sigunguCd'],
    '법정동코드': ['bjdongCd'],
    '지구분코드': ['platGbCd'],
    '번': ['bun'],
    '지': ['ji'],
    '관리건축물장PK': ['mgmBldrgstPk'],
    '장구분코드': ['regstrGbCd'],
    '장구분코드명': ['regstrGbCdNm'],
    '장종류코드': ['regstrKindCd'],
    '장종류코드명': ['regstrKindCdNm'],
    '도로명지위치': ['newPlatPlc'],
    '건물명': ['bldNm'],
    '특수지명': ['splotNm'],
    '블록': ['block'],
    '로트': ['lot'],
    '외필지수': ['bylotCnt'],
    '새주소도로코드': ['naRoadCd'],
    '새주소법정동코드': ['naBjdongCd'],
    '새주소지상지하코드': ['naUgrndCd'],
    '새주소본번': ['naMainBun'],
    '새주소부번': ['naSubBun'],
    '동명칭': ['dongNm'],
    '주부속구분코드': ['mainAtchGbCd'],
    '주부속구분코드명': ['mainAtchGbCdNm'],
    '지면적': ['platArea', '㎡'],
    '건축면적': ['archArea', '㎡'],
    '건폐율': ['bcRat', '%'],
    '연면적': ['totArea', '㎡'],
    '용적률산정연면적': ['vlRatEstmTotArea', '㎡'],
    '용적률': ['vlRat', '%'],
    '구조코드': ['strctCd'],
    '구조코드명': ['strctCdNm'],
    '기타구조': ['etcStrct'],
    '주용도코드': ['mainPurpsCd'],
    '내진설계적용여부': ['rserthqkDsgnApplyYn'],
    '내진능력': ['rserthqkAblty'],
}

export default outputs